# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "cancun"
  fuzz = { runs = 10_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "tests"
  libs = ["node_modules", "lib"]
  extra_output = ["storageLayout", "metadata"]
  ignored_error_codes = [2018, 2072, 5740, 3860, 8760, 5667] # 2072: unused parameter, 5740: unreachable code, 3860: contract size, 2018: function state mutability can be restricted to view
  verbosity = 0
  remappings = [
    "forge-std/=lib/forge-std/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelinV4/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelinV4/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "solady/=lib/solady/src/",
    "@prb/math/=lib/prb-math/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "permit2/=lib/permit2/src/"
  ]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_ETHERSCAN}" }
  base_sepolia = { key = "${API_KEY_ETHERSCAN}" }

[lint]
  exclude_lints = ["mixed-case-function", "asm-keccak256", "screaming-snake-case-immutable", "incorrect-shift", "mixed-case-variable"]
  ignore = ["./src/interfaces/**/*.sol", "./tests/**/*.sol", "./script/**/*.sol", "./src/external/**/*.sol"]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://mainnet.base.org"
  base_sepolia = "https://sepolia.base.org"
  intuition = "https://rpc.intuition.systems/http"
  intuition_sepolia = "https://testnet.rpc.intuition.systems/http"
  localhost = "http://localhost:8545"
  anvil = "http://127.0.0.1:8545"
  geth = "http://127.0.0.1:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
