# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "cancun"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 400
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "tests"
  libs = ["node_modules", "lib"]
  remappings = [
    "forge-std/=lib/forge-std/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelinV4/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelinV4/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "solady/=lib/solady/src/",
    "@prb/math/=lib/prb-math/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "@metalayer/=node_modules/@metalayer/contracts/src/",
    "permit2/=lib/permit2/src/"
  ]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_ETHERSCAN}" }
  base_sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-one-rpc.publicnode.com"
  base = "https://mainnet.base.org"
  base_sepolia = "https://sepolia.base.org"
  intuition = "https://intuition-testnet.rpc.caldera.xyz/http"
  intuition_sepolia = "https://intuition-testnet.rpc.caldera.xyz/http"
  localhost = "http://localhost:8545"
  anvil = "http://127.0.0.1:8545"
  geth = "http://127.0.0.1:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
