[profile.default]
evm_version = "cancun"                              # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
src = "src"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.27"
build_info = true
extra_output = ["storageLayout"]
auto_detect_remappings = false
fs_permissions = [{ access = "read", path = "./" }]
threads=0


[profile.ci]
fuzz_runs = 10_000
verbosity = 3


[profile.forktest]
optimizer = false
runs = 5


[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
