// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.29;

import { Test } from "forge-std/src/Test.sol";
import { console2 } from "forge-std/src/console2.sol";

import { ProxyAdmin } from "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import {
    ITransparentUpgradeableProxy
} from "@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol";
import { UpgradeableBeacon } from "@openzeppelin/contracts/proxy/beacon/UpgradeableBeacon.sol";

import { MultiVault } from "src/protocol/MultiVault.sol";
import { AtomWarden } from "src/protocol/wallet/AtomWarden.sol";

import { DeployCoreUpgradeImplementations } from "script/intuition/v1.1.0/DeployCoreUpgradeImplementations.s.sol";

/// @title  V1.1.0 upgrade address-book harness
/// @author 0xIntuition
/// @notice Exposes {DeployCoreUpgradeImplementations}'s internal address book and reinitializer
///         baseline to the parity test.
/// @dev    Exists so the test reads the upgrade script's OWN constants rather than a copy that
///         could silently drift. `_addresses` takes the chain id as a parameter and is `pure`, so
///         the harness never runs the script's `setUp` — which resolves `block.chainid` and would
///         revert inside a non-forked test.
contract V110AddressBookHarness is DeployCoreUpgradeImplementations {
    function addressBook(uint256 chainId) external pure returns (Addresses memory) {
        return _addresses(chainId);
    }

    /// @notice The AtomWarden reinitializer baseline, as the deploy script defines it.
    /// @dev    Returned from the script's own constants rather than its `setUp`-resolved state,
    ///         because `setUp` applies env overrides and the committed batches are deliberately
    ///         env-free.
    function atomWardenBaseline()
        external
        pure
        returns (
            uint256 claimWindow,
            uint256 minFeeThreshold,
            uint256 signatureThreshold,
            uint48 maxValidAfter,
            uint48 maxValidUntil,
            uint256 claimCapWindow
        )
    {
        return (
            DEFAULT_CLAIM_WINDOW,
            DEFAULT_MIN_FEE_THRESHOLD,
            DEFAULT_SIGNATURE_THRESHOLD,
            DEFAULT_MAX_VALID_AFTER,
            DEFAULT_MAX_VALID_UNTIL,
            DEFAULT_CLAIM_CAP_WINDOW
        );
    }
}

/// @title  V1.1.0 Safe TX-Builder calldata parity
/// @author 0xIntuition
/// @notice Byte-compares the committed Safe TX-Builder batches against calldata encoded
///         independently in Solidity, so a mis-encoded governance transaction is caught here
///         rather than in the Safe UI or on-chain.
/// @dev    The batches are generated by a TypeScript script using ethers; this test re-encodes the
///         same calls with `abi.encodeCall` and asserts byte equality. Two independent
///         implementations agreeing is the strongest verification available offline, and it is
///         cheap. Expectations come from {V110AddressBookHarness}, so the test reads the upgrade
///         script's OWN address book and reinitializer baseline rather than a copy that could
///         silently drift out of step with it.
///
///         The six implementation addresses are treated as free variables, extracted from the
///         JSON: they change with every deployment and the test must not need editing when they
///         do. Everything else — selectors, proxy and ProxyAdmin targets, ordering, empty upgrade
///         calldata, timelock parameters — is pinned.
///
///         Skips cleanly when the batches have not been generated yet, which is the repository's
///         state until the implementations are deployed.
/// @custom:upgrade v1.1.0
contract SafeBatchCalldataParityTest is Test {
    /// @dev Intuition Mainnet. The batches in `safe-txs/` are mainnet-only.
    uint256 internal constant BATCH_CHAIN_ID = 1155;

    string internal constant BATCH_DIR = "script/intuition/v1.1.0/safe-txs/";

    string internal constant SCHEDULE_FILE = "01-intuition-1155-upgrades-timelock-schedule.json";
    string internal constant EXECUTE_FILE = "02-intuition-1155-upgrades-timelock-execute.json";
    string internal constant MULTIVAULT_REINIT_FILE = "03-intuition-1155-admin-safe-multivault-reinitialize.json";
    string internal constant ATOM_WARDEN_REINIT_FILE = "04-intuition-1155-admin-safe-atomwarden-reinitialize.json";

    /// @dev The batches deliberately arm the per-window claim cap that the deploy script leaves
    ///      disabled by default. Pinned here so the divergence stays intentional: if the batches
    ///      ever silently fall back to the script's `0`, this test fails.
    uint256 internal constant EXPECTED_MAX_CLAIMS_PER_WINDOW = 100;

    /// @dev The upgrade covers exactly these six targets, in this order.
    uint256 internal constant EXPECTED_UPGRADE_COUNT = 6;

    /// @dev `getMinDelay()` on the Upgrades Timelock, verified on-chain 2026-07-27. Pinned rather
    ///      than merely required to be non-zero: a batch scheduled with a shorter delay than the
    ///      timelock enforces reverts, and one scheduled with a longer delay silently stretches the
    ///      release window.
    uint256 internal constant EXPECTED_TIMELOCK_DELAY = 604_800;

    /// @dev The generator derives the operation salt from this fixed release string. Pinning it
    ///      makes the timelock operation id reproducible from the repository alone, and catches a
    ///      salt that drifted in BOTH batch files at once (which would otherwise still look
    ///      self-consistent).
    string internal constant TIMELOCK_SALT_PREIMAGE = "intuition-core-upgrade-v1.1.0";

    /// @dev The upgrade's own address book, read through the harness.
    DeployCoreUpgradeImplementations.Addresses internal addr;

    /// @dev The Parameters TimelockController that `MultiVault.reinitialize` bootstraps.
    address internal parametersTimelock;

    uint256 internal reinitClaimWindow;
    uint256 internal reinitMinFeeThreshold;
    uint256 internal reinitSignatureThreshold;
    uint48 internal reinitMaxValidAfter;
    uint48 internal reinitMaxValidUntil;
    uint256 internal reinitClaimCapWindow;

    function setUp() public {
        V110AddressBookHarness harness = new V110AddressBookHarness();

        addr = harness.addressBook(BATCH_CHAIN_ID);
        parametersTimelock = addr.parametersTimelock;

        (
            reinitClaimWindow,
            reinitMinFeeThreshold,
            reinitSignatureThreshold,
            reinitMaxValidAfter,
            reinitMaxValidUntil,
            reinitClaimCapWindow
        ) = harness.atomWardenBaseline();
    }

    /* =================================================== */
    /*                    Timelock Batch                   */
    /* =================================================== */

    /// @notice The scheduled timelock operation upgrades exactly the six covered contracts, each
    ///         with empty calldata, targeting the right ProxyAdmin or beacon.
    function test_scheduleBatch_matchesSolidityEncoding() external {
        _requireBatches();

        bytes memory data = _transactionData(SCHEDULE_FILE, 0);

        (
            address[] memory targets,
            uint256[] memory values,
            bytes[] memory payloads,
            bytes32 predecessor,
            bytes32 salt,
            uint256 delay
        ) = abi.decode(_stripSelector(data), (address[], uint256[], bytes[], bytes32, bytes32, uint256));

        assertEq(bytes4(data), bytes4(keccak256("scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)")));
        assertEq(targets.length, EXPECTED_UPGRADE_COUNT, "upgrade count");
        assertEq(values.length, EXPECTED_UPGRADE_COUNT, "values length");
        assertEq(payloads.length, EXPECTED_UPGRADE_COUNT, "payloads length");
        assertEq(predecessor, bytes32(0), "predecessor must be empty");
        assertEq(delay, EXPECTED_TIMELOCK_DELAY, "delay must equal the timelock minDelay");
        assertEq(salt, keccak256(bytes(TIMELOCK_SALT_PREIMAGE)), "salt must be the release salt");

        _assertUpgradePayloads(targets, values, payloads);
    }

    /// @notice The execute batch replays the schedule batch byte for byte.
    /// @dev    The timelock recomputes the operation id from these arguments, so any divergence
    ///         between the two files makes execution revert. Asserting equality here catches that
    ///         at authoring time rather than after a seven-day wait.
    function test_executeBatch_matchesScheduleBatch() external {
        _requireBatches();

        bytes memory scheduleData = _transactionData(SCHEDULE_FILE, 0);
        bytes memory executeData = _transactionData(EXECUTE_FILE, 0);

        (
            address[] memory scheduleTargets,
            uint256[] memory scheduleValues,
            bytes[] memory schedulePayloads,
            bytes32 schedulePredecessor,
            bytes32 scheduleSalt,
        ) = abi.decode(_stripSelector(scheduleData), (address[], uint256[], bytes[], bytes32, bytes32, uint256));

        (
            address[] memory executeTargets,
            uint256[] memory executeValues,
            bytes[] memory executePayloads,
            bytes32 executePredecessor,
            bytes32 executeSalt
        ) = abi.decode(_stripSelector(executeData), (address[], uint256[], bytes[], bytes32, bytes32));

        assertEq(bytes4(executeData), bytes4(keccak256("executeBatch(address[],uint256[],bytes[],bytes32,bytes32)")));
        assertEq(executeSalt, keccak256(bytes(TIMELOCK_SALT_PREIMAGE)), "salt must be the release salt");
        assertEq(
            keccak256(abi.encode(scheduleTargets, scheduleValues, schedulePayloads, schedulePredecessor, scheduleSalt)),
            keccak256(abi.encode(executeTargets, executeValues, executePayloads, executePredecessor, executeSalt)),
            "schedule and execute describe different timelock operations"
        );
    }

    /// @notice Both timelock batches are sent to the Upgrades Timelock, not to a ProxyAdmin.
    function test_timelockBatches_targetTheUpgradesTimelock() external {
        _requireBatches();

        assertEq(_transactionTo(SCHEDULE_FILE, 0), addr.upgradesTimelock, "schedule target");
        assertEq(_transactionTo(EXECUTE_FILE, 0), addr.upgradesTimelock, "execute target");
    }

    /* =================================================== */
    /*                     Reinitializers                  */
    /* =================================================== */

    /// @notice `MultiVault.reinitialize` bootstraps the Parameters TimelockController the deploy
    ///         script resolves, and is sent to the MultiVault proxy itself — not its ProxyAdmin.
    function test_multiVaultReinitialize_matchesSolidityEncoding() external {
        _requireBatches();

        assertEq(_transactionTo(MULTIVAULT_REINIT_FILE, 0), addr.multiVaultProxy, "must target the proxy");
        assertEq(
            _transactionData(MULTIVAULT_REINIT_FILE, 0),
            abi.encodeCall(MultiVault.reinitialize, (parametersTimelock)),
            "MultiVault.reinitialize calldata"
        );
    }

    /// @notice `AtomWarden.reinitialize` matches the deploy script's baseline on every parameter
    ///         except the deliberately-armed claim cap.
    function test_atomWardenReinitialize_matchesSolidityEncoding() external {
        _requireBatches();

        assertEq(_transactionTo(ATOM_WARDEN_REINIT_FILE, 0), addr.atomWardenProxy, "must target the proxy");
        assertEq(
            _transactionData(ATOM_WARDEN_REINIT_FILE, 0),
            abi.encodeCall(
                AtomWarden.reinitialize,
                (
                    reinitClaimWindow,
                    reinitMinFeeThreshold,
                    reinitSignatureThreshold,
                    reinitMaxValidAfter,
                    reinitMaxValidUntil,
                    EXPECTED_MAX_CLAIMS_PER_WINDOW,
                    reinitClaimCapWindow
                )
            ),
            "AtomWarden.reinitialize calldata"
        );
    }

    /// @notice The claim cap ships armed. Guards the one intentional divergence from the deploy
    ///         script's defaults, so an accidental fallback to the disabled `0` fails loudly.
    function test_atomWardenReinitialize_armsTheClaimCap() external {
        _requireBatches();

        (,,,,, uint256 maxClaimsPerWindow,) = abi.decode(
            _stripSelector(_transactionData(ATOM_WARDEN_REINIT_FILE, 0)),
            (uint256, uint256, uint256, uint48, uint48, uint256, uint256)
        );

        assertEq(maxClaimsPerWindow, EXPECTED_MAX_CLAIMS_PER_WINDOW, "claim cap must be armed, not 0");
    }

    /* =================================================== */
    /*                     Batch Metadata                  */
    /* =================================================== */

    /// @notice Every batch is built for chain 1155 and carries no value.
    /// @dev    A batch imported into a Safe on the wrong chain, or one that moves native value,
    ///         is a whole class of mistake this cheap check removes.
    function test_batchMetadata_isCorrect() external {
        _requireBatches();

        string[4] memory files = [SCHEDULE_FILE, EXECUTE_FILE, MULTIVAULT_REINIT_FILE, ATOM_WARDEN_REINIT_FILE];

        for (uint256 i = 0; i < files.length; ++i) {
            string memory json = vm.readFile(string.concat(BATCH_DIR, files[i]));
            assertEq(vm.parseJsonString(json, ".chainId"), "1155", "chainId");
            assertEq(vm.parseJsonString(json, ".transactions[0].value"), "0", "value must be 0");
        }
    }

    /* =================================================== */
    /*                       Helpers                       */
    /* =================================================== */

    /// @dev Re-encodes each upgrade with `abi.encodeCall` and byte-compares it against the
    ///      generated payload. The implementation address is read back out of the payload rather
    ///      than hardcoded, so this survives every redeployment; the proxy, the ProxyAdmin target
    ///      and the empty calldata are pinned.
    function _assertUpgradePayloads(address[] memory targets, uint256[] memory values, bytes[] memory payloads)
        internal
        view
    {
        address[6] memory expectedTargets = [
            addr.multiVaultProxyAdmin,
            addr.trustBondingProxyAdmin,
            addr.atomWardenProxyAdmin,
            addr.atomWalletBeacon,
            addr.linearCurveProxyAdmin,
            addr.offsetProgressiveCurveProxyAdmin
        ];

        address[6] memory expectedProxies = [
            addr.multiVaultProxy,
            addr.trustBondingProxy,
            addr.atomWardenProxy,
            address(0), // AtomWallet is a beacon: it upgrades itself, there is no separate proxy.
            addr.linearCurveProxy,
            addr.offsetProgressiveCurveProxy
        ];

        for (uint256 i = 0; i < EXPECTED_UPGRADE_COUNT; ++i) {
            assertEq(targets[i], expectedTargets[i], "upgrade target");
            assertEq(values[i], 0, "upgrade must not move value");

            if (expectedProxies[i] == address(0)) {
                // Beacon swap: `UpgradeableBeacon.upgradeTo(address)`.
                address newImplementation = abi.decode(_stripSelector(payloads[i]), (address));
                assertEq(
                    payloads[i],
                    abi.encodeCall(UpgradeableBeacon.upgradeTo, (newImplementation)),
                    "beacon upgradeTo calldata"
                );
                continue;
            }

            // Transparent proxy: `ProxyAdmin.upgradeAndCall(proxy, impl, "")`.
            (address proxy, address implementation, bytes memory initData) =
                abi.decode(_stripSelector(payloads[i]), (address, address, bytes));

            assertEq(proxy, expectedProxies[i], "upgraded proxy");
            assertEq(
                initData.length,
                0,
                "upgradeAndCall must carry EMPTY calldata: embedded reinit runs as the ProxyAdmin and reverts"
            );
            assertEq(
                payloads[i],
                abi.encodeCall(ProxyAdmin.upgradeAndCall, (ITransparentUpgradeableProxy(proxy), implementation, "")),
                "upgradeAndCall calldata"
            );
        }
    }

    /// @dev The batches are committed only after the implementations are deployed. Until then the
    ///      suite must not fail on a file that does not exist yet — but it must not report a
    ///      PASS either, because no parity assertion has run. `vm.skip` makes the gap visible in
    ///      the runner output instead of hiding it behind a green tick.
    function _requireBatches() internal {
        try vm.readFile(string.concat(BATCH_DIR, SCHEDULE_FILE)) returns (string memory) {
            return;
        } catch {
            console2.log("v1.1.0 Safe batches not generated yet (implementations not deployed).");
            vm.skip(true);
        }
    }

    function _transactionData(string memory file, uint256 index) internal view returns (bytes memory) {
        string memory json = vm.readFile(string.concat(BATCH_DIR, file));
        return vm.parseJsonBytes(json, string.concat(".transactions[", vm.toString(index), "].data"));
    }

    function _transactionTo(string memory file, uint256 index) internal view returns (address) {
        string memory json = vm.readFile(string.concat(BATCH_DIR, file));
        return vm.parseJsonAddress(json, string.concat(".transactions[", vm.toString(index), "].to"));
    }

    /// @dev Drops the 4-byte selector so the remainder can be `abi.decode`d.
    function _stripSelector(bytes memory data) internal pure returns (bytes memory) {
        require(data.length >= 4, "calldata too short");

        bytes memory stripped = new bytes(data.length - 4);
        for (uint256 i = 0; i < stripped.length; ++i) {
            stripped[i] = data[i + 4];
        }

        return stripped;
    }
}
